Up cd.yml - fix (change localhost to dns service names)

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -63,8 +63,13 @@ jobs:
           for SERVICE in "${!SERVICE_PORTS[@]}"; do
             PORT=${SERVICE_PORTS[$SERVICE]}
             POD=$(kubectl get pods -l app=$SERVICE -o jsonpath="{.items[0].metadata.name}")
+            
             echo "Checking /actuator/health for pod $POD of service $SERVICE on port $PORT..."
-            kubectl exec "$POD" -- curl -f http://localhost:$PORT/actuator/health || { echo "Health check failed for $SERVICE"; exit 1; }
+            
+            kubectl exec "$POD" -- curl -f http://$SERVICE:$PORT/actuator/health || {
+            echo "Health check failed for $SERVICE";
+            exit 1;
+          }
           done
 
       - name: Finish
